title: Hongwei Wu
logo: /assets/img/personal_pic.png
description: Ph.D. student at Purdue University
show_downloads: false
google_analytics: UA-152715299-1
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

url: 'https://hwu71.github.io'

author: Hongwei Wu

social_links:
  name: Hongwei Wu
  email: "mailto:wu1685@purdue.edu"
  github: "https://github.com/hwu71"
  linkedin: "https://www.linkedin.com/in/hongwei-wu/"
