title: Hongwei Wu
logo: /assets/img/Bibabo.png
description: Ph.D. student at Purdue University
show_downloads: false
google_analytics: UA-152715299-1
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

url: 'https://hwu71.github.io'

author: Hongwei Wu                 # change to your full name

github:
  username: hwu71             # change to your github username

twitter:
  username: darkocobe            # change to your twitter username

social:
  name: Hongwei Wu                  # it will shows as the copyright owner in Footer
  email: wu1685@purdue.edu             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/darkocobe      # change to your twitter homepage
    - https://github.com/hwu71       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/hongwei-wu/