layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: hongwei-wu/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://hwu71.github.io/
  # youtube: your_username

topics:
  - name: C/C++
    web_url: https://github.com/hwu71/PinOnWindows
    image_url: ../photos/c-cpp.png

  - name: JavaScript/HTML/CSS
    web_url: https://github.com/hwu71/RUCMarket
    image_url: ../photos/html-css-js.jpg

  - name: Assembly Language
    web_url: https://github.com/hwu71/ROP_attacks_and_defense
    image_url: ../photos/asm.png
    
  - name: Solidity
    web_url: https://github.com/hwu71/RUCMarket
    image_url: ../photos/solidity.png
    
  - name: Intel Pin
    web_url: https://github.com/hwu71/PinOnWindows
    image_url: ../photos/pin.jpg
    
  - name: IDA Pro
    web_url: https://www.hex-rays.com/products/ida/
    image_url: ../photos/ida.png
    
    
events:
  - note: IBM Vault
    description: The final stage is a hacking competition at the IBM X-Force Command Center and my team won the second place!
    location: Boston, MA
    time: 2018-10
    web_url: https://www.ibm.com/employment/vault/
    image_url01: ../photos/ibm01.jpg
    image_url02: ../photos/ibm02.jpg

  - note: National Information Security Competition of China
    description: My team presented our Password Management System at the final and won the second prize!
    location: Wuhan, China
    time: 2018-08
    web_url: https://github.com/hwu71/Password-Management-System-Based-on-Living-body-Authentication
    image_url01: ../photos/sec01.jpg
    image_url02: ../photos/sec02.jpg